// apps/demo-svelte/src/App.svelte
<frame>
    {#if currentScreen === 'home'}
        <Home on:navigate={handleNavigate} />
    {:else if currentScreen === 'demo'}
        <StreamdownDemo on:back={goBack} />
    {:else if currentScreen === 'chat'}
        <ChatDemo on:back={goBack} />
    {:else if currentScreen === 'charts'}
        <ChartsHome on:navigate={handleNavigate} on:back={goBack} />
    {:else if currentScreen === 'line'}
        <LineChartDemo on:back={goBack} />
    {:else if currentScreen === 'bar'}
        <BarChartDemo on:back={goBack} />
    {:else if currentScreen === 'pie'}
        <PieChartDemo on:back={goBack} />
    {/if}
</frame>

<script lang="ts">
    import Home from './components/Home.svelte';
    import StreamdownDemo from './components/StreamdownDemo.svelte';
    import ChatDemo from './components/ChatDemo.svelte';
    import ChartsHome from './components/ChartsHome.svelte';
    import LineChartDemo from './components/LineChartDemo.svelte';
    import BarChartDemo from './components/BarChartDemo.svelte';
    import PieChartDemo from './components/PieChartDemo.svelte';

    let currentScreen = 'home';

    function handleNavigate(event: CustomEvent<string>) {
        currentScreen = event.detail;
    }

    function goBack() {
        // If we're in a chart demo, go back to charts home
        if (['line', 'bar', 'pie'].includes(currentScreen)) {
            currentScreen = 'charts';
        } else {
            currentScreen = 'home';
        }
    }
</script>

// apps/demo-vue/src/App.vue
<script lang="ts" setup>
import { ref } from 'vue';
import Home from './components/Home.vue';
import StreamdownDemo from './components/StreamdownDemo.vue';
import ChatDemo from './components/ChatDemo.vue';
import ChartsHome from './components/ChartsHome.vue';
import LineChartDemo from './components/LineChartDemo.vue';
import BarChartDemo from './components/BarChartDemo.vue';
import PieChartDemo from './components/PieChartDemo.vue';

const currentScreen = ref<'home' | 'demo' | 'chat' | 'charts' | 'line' | 'bar' | 'pie'>('home');
const navigationKey = ref(0);

const navigate = (screen: 'home' | 'demo' | 'chat' | 'charts' | 'line' | 'bar' | 'pie') => {
  navigationKey.value++;
  currentScreen.value = screen;
};

const goBack = () => {
  navigationKey.value++;
  // If in a chart sub-screen, go back to charts home
  if (['line', 'bar', 'pie'].includes(currentScreen.value)) {
    currentScreen.value = 'charts';
  } else {
    currentScreen.value = 'home';
  }
};
</script>

<template>
  <Frame id="main-frame" :key="navigationKey">
    <Home v-if="currentScreen === 'home'" @navigate="navigate" />
    <StreamdownDemo v-else-if="currentScreen === 'demo'" @back="goBack" />
    <ChatDemo v-else-if="currentScreen === 'chat'" @back="goBack" />
    <ChartsHome v-else-if="currentScreen === 'charts'" @back="goBack" @navigate="navigate" />
    <LineChartDemo v-else-if="currentScreen === 'line'" @back="goBack" />
    <BarChartDemo v-else-if="currentScreen === 'bar'" @back="goBack" />
    <PieChartDemo v-else-if="currentScreen === 'pie'" @back="goBack" />
  </Frame>
</template>
