// apps/demo-angular/src/app/demos/chat-demo.ts
/**
 * Chat Demo Component
 * Interactive AI chat interface demonstrating real-time streaming
 */
import { Component, NO_ERRORS_SCHEMA, ChangeDetectionStrategy, signal, ViewChild, ElementRef } from '@angular/core';
import { NativeScriptCommonModule, RouterExtensions } from '@nativescript/angular';
import { ScrollView, View } from '@nativescript/core';
import { Streamdown } from '@nstudio/nstreamdown/angular';
import type { StreamdownConfig } from '@nstudio/nstreamdown/angular';
import { showMenu, MenuConfig } from '../utils';

interface ChatMessage {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  isStreaming: boolean;
}

// Sample AI responses for different prompts
const AI_RESPONSES: Record<string, string> = {
  default: `I'd be happy to help! I'm a demo of **NativeScript Streamdown**, showcasing real-time AI streaming on iOS.

Here's what I can demonstrate:

1. **Streaming text** that appears word by word
2. \`Code snippets\` with syntax highlighting
3. Mathematical expressions like $E = mc^2$
4. Tables, lists, and more!

What would you like to see?`,

  code: `Here's a **TypeScript** example showing how to use Streamdown:

\`\`\`typescript
import { StreamdownComponent } from './streamdown';

@Component({
  selector: 'app-chat',
  template: \`
    <Streamdown
      [content]="aiResponse"
      [config]="{ mode: 'streaming' }"
    ></Streamdown>
  \`
})
export class ChatComponent {
  aiResponse = '';

  async streamResponse(prompt: string) {
    const response = await fetch('/api/chat', {
      method: 'POST',
      body: JSON.stringify({ prompt })
    });

    const reader = response.body.getReader();
    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      this.aiResponse += new TextDecoder().decode(value);
    }
  }
}
\`\`\`

This creates a smooth streaming experience! ✨`,

  table: `Here's a comparison **table**:

| Staying In | Going Out | Outdoors | Habits |
|-----------|----------|-------------|----------------|
| Energy level | Low | Medium | Medium |
| Main feature | Comfort | Variety | Medium |
| Snacks | Popcorn | Spontaneous | Higher |

### Key Takeaways:
- **NativeScript** provides true native UI
- Direct access to native platform APIs
- Use Angular, Vue, Solid, React, or Svelte!`,

  math: `Let me show you some **mathematical expressions**:

### Quadratic Formula
$$x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a}$$

### Euler's Identity
The most beautiful equation in mathematics:
$$e^{i\\pi} + 1 = 0$$

### Inline Math
You can also use inline math like $\\sum_{i=1}^{n} i = \\frac{n(n+1)}{2}$ within text.

### Calculus
$$\\int_{0}^{\\infty} e^{-x^2} dx = \\frac{\\sqrt{\\pi}}{2}$$

Pretty cool, right? 🧮`,

  hello: `# Hello! 👋

Nice to meet you! I'm running **natively** through NativeScript.

## What makes this special?

> *Every element you see is a native platform view*

### Benefits:
- ⚡ Native performance
- 🎨 Platform-specific styling
- 📱 Smooth scrolling
- 🔧 Direct API access

Use the **⋯** menu to explore more demos!`,
};

@Component({
  selector: 'ChatDemo',
  template: `
    <GridLayout rows="auto, *, auto" class="bg-slate-100 dark:bg-slate-900">
      <!-- Native ActionBar -->
      <ActionBar flat="true" class="text-black dark:text-white bg-slate-50 dark:bg-slate-900" title="AI Chat">
        <NavigationButton text="" android.systemIcon="ic_menu_back" (tap)="goBack()"></NavigationButton>
        <ActionItem ios.position="right" (tap)="clearChat()">
          <Image src="sys://trash" class="w-5 h-5 text-red-500"></Image>
        </ActionItem>
      </ActionBar>

      <!-- Messages -->
      <ScrollView row="1" #scrollView>
        <StackLayout class="p-4">
          @for (message of messages(); track $index) {
            <!-- User message -->
            @if (message.role === 'user') {
              <GridLayout columns="*, auto" class="mb-3">
                <StackLayout col="1" class="bg-blue-600 dark:bg-blue-700 rounded-2xl rounded-br-sm py-2 px-3 max-w-[280]">
                  <Label [text]="message.content" class="text-white text-sm leading-[3]" textWrap="true"></Label>
                </StackLayout>
              </GridLayout>
            }

            <!-- Assistant message -->
            @if (message.role === 'assistant') {
              <GridLayout columns="30, *" class="mb-3">
                <!-- Avatar - using GridLayout for vertical centering -->
                <GridLayout col="0" rows="26" columns="26" class="bg-purple-600 dark:bg-purple-700 rounded-full mr-1 h-[26] w-[26]">
                  <Label text="AI" class="text-white text-[10] font-bold text-center"></Label>
                </GridLayout>

                <!-- Message bubble -->
                <StackLayout col="1" class="bg-white dark:bg-slate-800 rounded-2xl rounded-tl-sm py-2 px-3 shadow-sm">
                  <Streamdown [content]="message.content" [config]="getMessageConfig(message)"></Streamdown>
                </StackLayout>
              </GridLayout>
            }
          }

          <!-- Typing indicator -->
          @if (isTyping()) {
            <GridLayout columns="30, auto" class="mb-3">
              <GridLayout col="0" rows="26" columns="26" class="bg-purple-600 dark:bg-purple-700 rounded-full mr-1 h-[26] w-[26]">
                <Label text="AI" class="text-white text-[10] font-bold text-center"></Label>
              </GridLayout>
              <StackLayout col="1" class="bg-white dark:bg-slate-800 rounded-2xl py-2 px-3 shadow-sm">
                <Label text="•••" class="text-slate-400 dark:text-slate-500 text-base"></Label>
              </StackLayout>
            </GridLayout>
          }
        </StackLayout>
      </ScrollView>

      <!-- Bottom menu bar -->
      <GridLayout row="2" columns="*, auto" class="bg-white dark:bg-slate-800 px-4 py-3 border-t border-slate-200 dark:border-slate-700">
        <Label col="0" text="Tap menu to explore demos" class="text-xs text-slate-400 dark:text-slate-500"></Label>
        <StackLayout col="1" #menuAnchor class="bg-slate-100 dark:bg-slate-700 rounded-lg px-3 py-2" (tap)="showOptionsMenu($event)">
          <Label text="⋯" class="text-sm text-slate-600 dark:text-slate-300 font-medium"></Label>
        </StackLayout>
      </GridLayout>
    </GridLayout>
  `,
  imports: [NativeScriptCommonModule, Streamdown],
  schemas: [NO_ERRORS_SCHEMA],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ChatDemo {
  @ViewChild('scrollView') scrollViewRef!: ElementRef;
  @ViewChild('menuAnchor') menuAnchorRef!: ElementRef;

  messages = signal<ChatMessage[]>([
    {
      id: '1',
      role: 'assistant',
      content: AI_RESPONSES.hello,
      isStreaming: false,
    },
  ]);

  isTyping = signal(false);

  constructor(private routerExtensions: RouterExtensions) {}

  getMessageConfig(message: ChatMessage): StreamdownConfig {
    return {
      mode: message.isStreaming ? 'streaming' : 'static',
      controls: true,
      showCaret: message.isStreaming,
    };
  }

  async showOptionsMenu(args: any) {
    const view = args.object as View;

    const config: MenuConfig = {
      title: 'Demo Options',
      items: [
        { id: 'code', title: 'Show Code Example', icon: 'doc.text' },
        { id: 'table', title: 'Show Table', icon: 'tablecells' },
        { id: 'math', title: 'Show Math', icon: 'function' },
        {
          id: 'default',
          title: 'What can you do?',
          icon: 'questionmark.circle',
        },
      ],
    };

    const result = await showMenu(view, config);
    console.log('result:', result);
    if (result) {
      this.sendPrompt(result.itemId);
    }
  }

  sendPrompt(key: string) {
    const promptLabels: Record<string, string> = {
      code: 'Show me a code example',
      table: 'Show me a table',
      math: 'Show me math equations',
      default: 'What can you do?',
    };

    const userMessage: ChatMessage = {
      id: Date.now().toString(),
      role: 'user',
      content: promptLabels[key] || key,
      isStreaming: false,
    };

    this.messages.set([...this.messages(), userMessage]);
    this.isTyping.set(true);
    this.scrollToBottom();

    setTimeout(() => {
      // allow render update on next tick
      this.isTyping.set(false);
      setTimeout(() => {
        // now simulate streaming response
        this.streamResponse(key);
      });
    }, 500);
  }

  private streamResponse(key: string) {
    const fullResponse = AI_RESPONSES[key] || AI_RESPONSES.default;
    const chunks = fullResponse.split(/(?<=\s)/);

    const messageId = Date.now().toString();
    const streamingMessage: ChatMessage = {
      id: messageId,
      role: 'assistant',
      content: '',
      isStreaming: true,
    };

    this.messages.set([...this.messages(), streamingMessage]);

    let chunkIndex = 0;
    const interval = setInterval(() => {
      if (chunkIndex < chunks.length) {
        const currentMessages = this.messages();
        const messageIndex = currentMessages.findIndex((m) => m.id === messageId);

        if (messageIndex !== -1) {
          const updatedMessages = [...currentMessages];
          updatedMessages[messageIndex] = {
            ...updatedMessages[messageIndex],
            content: updatedMessages[messageIndex].content + chunks[chunkIndex],
          };
          this.messages.set(updatedMessages);
          this.scrollToBottom();
        }

        chunkIndex++;
      } else {
        clearInterval(interval);

        const currentMessages = this.messages();
        const messageIndex = currentMessages.findIndex((m) => m.id === messageId);
        if (messageIndex !== -1) {
          const updatedMessages = [...currentMessages];
          updatedMessages[messageIndex] = {
            ...updatedMessages[messageIndex],
            isStreaming: false,
          };
          this.messages.set(updatedMessages);
        }
      }
    }, 25);
  }

  private scrollToBottom() {
    if (this.scrollViewRef?.nativeElement) {
      const scrollView = this.scrollViewRef.nativeElement as ScrollView;
      setTimeout(() => {
        scrollView.scrollToVerticalOffset(scrollView.scrollableHeight, false);
      }, 10);
    }
  }

  clearChat() {
    this.messages.set([
      {
        id: '1',
        role: 'assistant',
        content: AI_RESPONSES.hello,
        isStreaming: false,
      },
    ]);
  }

  goBack() {
    this.routerExtensions.back();
  }
}

// apps/demo-svelte/src/components/ChatDemo.svelte
<page>
    <actionBar flat={true} class="bg-slate-50" title="Chat Demo">
        <navigationButton text="" android={{ systemIcon: 'ic_menu_back' }} on:tap={() => dispatch('back')} />
    </actionBar>

    <gridLayout rows="*, auto" class="bg-slate-100">
        <!-- Messages list -->
        <scrollView row="0" bind:this={scrollViewRef}>
            <stackLayout class="p-4">
                {#if messages.length === 0}
                    <stackLayout class="items-center my-8">
                        <label text="💬" class="text-4xl mb-4" />
                        <label text="Start a conversation" class="text-lg font-semibold text-slate-700" />
                        <label text="Try the suggestions below" class="text-sm text-slate-500 mt-1" />

                        <!-- Quick action buttons -->
                        <stackLayout class="mt-6 w-full px-4">
                            <label
                                text="Show me a TypeScript example"
                                class="bg-white rounded-lg p-3 mb-2 text-slate-700 shadow-sm"
                                on:tap={() => onQuickAction('Show me a TypeScript example')}
                            />
                            <label
                                text="Explain the quadratic formula"
                                class="bg-white rounded-lg p-3 mb-2 text-slate-700 shadow-sm"
                                on:tap={() => onQuickAction('Explain the quadratic formula')}
                            />
                            <label
                                text="What makes Streamdown special?"
                                class="bg-white rounded-lg p-3 mb-2 text-slate-700 shadow-sm"
                                on:tap={() => onQuickAction('What makes Streamdown special?')}
                            />
                        </stackLayout>
                    </stackLayout>
                {/if}

                {#each messages as message (message.id)}
                    <gridLayout
                        columns={message.isUser ? '*, auto' : 'auto, *'}
                        class="mb-3"
                    >
                        {#if message.isUser}
                            <stackLayout col="1" class="bg-blue-500 rounded-2xl rounded-br-sm px-4 py-3 max-w-[80%]">
                                <label text={message.content} class="text-white" textWrap={true} />
                            </stackLayout>
                        {:else}
                            <stackLayout col="0" class="bg-white rounded-2xl rounded-bl-sm px-4 py-3 max-w-[85%] shadow-sm">
                                <Streamdown content={message.streamedContent} {config} />
                                {#if message.isStreaming}
                                    <label text="..." class="text-slate-400 text-xs mt-1" />
                                {/if}
                            </stackLayout>
                        {/if}
                    </gridLayout>
                {/each}
            </stackLayout>
        </scrollView>

        <!-- Input area -->
        <gridLayout row="1" columns="*, auto" class="bg-white border-t-[1] border-slate-200 px-4 py-3">
            <textView
                col="0"
                text={inputText}
                on:textChange={(e) => (inputText = e.value)}
                hint="Ask something..."
                class="bg-slate-100 rounded-full px-4 py-2 text-base"
                returnKeyType="send"
            />
            <label
                col="1"
                text="↑"
                class={`ml-2 w-10 h-10 rounded-full text-center text-white text-lg font-bold leading-10 ${
                    inputText.trim() && !isProcessing ? 'bg-blue-500' : 'bg-slate-300'
                }`}
                on:tap={sendMessage}
            />
        </gridLayout>
    </gridLayout>
</page>

<script lang="ts">
    import { createEventDispatcher, onDestroy } from 'svelte';
    import { Streamdown } from '@nstudio/nstreamdown/svelte';

    const dispatch = createEventDispatcher();

    interface ChatMessage {
        id: number;
        content: string;
        isUser: boolean;
        isStreaming: boolean;
        streamedContent: string;
        startTime?: number;
    }

    const AI_RESPONSES = [
        `Here's a **TypeScript** example for you:

\`\`\`typescript
interface User {
  id: number;
  name: string;
  email: string;
}

async function fetchUser(id: number): Promise<User> {
  const response = await fetch(\`/api/users/\${id}\`);
  return response.json();
}
\`\`\`

This demonstrates async/await with proper typing!`,

        `Great question! Here's how you can use **NativeScript** with Vue:

\`\`\`vue
<template>
  <Page>
    <ActionBar title="My App" />
    <StackLayout>
      <Label :text="message" />
      <Button text="Click me" @tap="onTap" />
    </StackLayout>
  </Page>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

export default defineComponent({
  data() {
    return { message: 'Hello NativeScript!' };
  },
  methods: {
    onTap() {
      this.message = 'Button tapped!';
    }
  }
});
<\/script>
\`\`\``,

        `# Streamdown Features 🎯

Here's what makes Streamdown special:

| Feature | Description |
|---------|-------------|
| **Streaming** | Real-time token rendering |
| **Syntax Highlighting** | Beautiful code blocks |
| **Math Support** | LaTeX rendering: $E = mc^2$ |
| **Native Performance** | Built for iOS & Android |

> "Performance is not just a feature, it's the foundation."

## Why Choose Streamdown?

1. **Speed**: Optimized for real-time AI responses
2. **Flexibility**: Works with any LLM API
3. **Native**: True native rendering, not a web view`,

        `Let me explain **async/await** in JavaScript:

\`\`\`javascript
// Without async/await
fetch('/api/data')
  .then(response => response.json())
  .then(data => console.log(data))
  .catch(error => console.error(error));

// With async/await
async function getData() {
  try {
    const response = await fetch('/api/data');
    const data = await response.json();
    console.log(data);
  } catch (error) {
    console.error(error);
  }
}
\`\`\`

Much cleaner, right? ✨`,

        `Here's the **quadratic formula** explained:

$$
x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a}
$$

Where:
- $a$ is the coefficient of $x^2$
- $b$ is the coefficient of $x$  
- $c$ is the constant term

### Example

For $2x^2 + 5x + 3 = 0$:

- $a = 2$, $b = 5$, $c = 3$
- $x = \\frac{-5 \\pm \\sqrt{25 - 24}}{4}$
- $x = \\frac{-5 \\pm 1}{4}$

So $x = -1$ or $x = -1.5$`
    ];

    let messages: ChatMessage[] = [];
    let inputText = '';
    let isProcessing = false;
    let responseIndex = 0;

    let scrollViewRef: any = null;
    let messageId = 0;
    let streamInterval: any = null;

    const config = {
        mode: 'streaming' as const,
        controls: true,
        showCaret: true,
        caret: '▋',
    };

    onDestroy(() => {
        if (streamInterval) {
            clearInterval(streamInterval);
        }
    });

    function scrollToBottom() {
        setTimeout(() => {
            if (scrollViewRef) {
                scrollViewRef.scrollToVerticalOffset(
                    scrollViewRef.scrollableHeight || 0,
                    true
                );
            }
        }, 100);
    }

    function sendMessage() {
        if (!inputText.trim() || isProcessing) return;

        const userMessage: ChatMessage = {
            id: ++messageId,
            content: inputText,
            isUser: true,
            isStreaming: false,
            streamedContent: inputText,
        };

        messages = [...messages, userMessage];
        inputText = '';
        isProcessing = true;
        scrollToBottom();

        // Simulate AI response delay
        setTimeout(() => {
            const aiMessage: ChatMessage = {
                id: ++messageId,
                content: AI_RESPONSES[responseIndex % AI_RESPONSES.length],
                isUser: false,
                isStreaming: true,
                streamedContent: '',
                startTime: Date.now(),
            };

            messages = [...messages, aiMessage];
            responseIndex++;
            startStreamingMessage(aiMessage);
            scrollToBottom();
        }, 500);
    }

    function startStreamingMessage(message: ChatMessage) {
        const chunks = message.content.split(/(?<=\s)/);
        let chunkIndex = 0;

        streamInterval = setInterval(() => {
            if (chunkIndex < chunks.length) {
                const chunksToProcess = Math.min(2, chunks.length - chunkIndex);
                let newContent = '';
                for (let j = 0; j < chunksToProcess; j++) {
                    newContent += chunks[chunkIndex + j];
                }
                chunkIndex += chunksToProcess;

                messages = messages.map((m) =>
                    m.id === message.id
                        ? { ...m, streamedContent: m.streamedContent + newContent }
                        : m
                );
                scrollToBottom();
            } else {
                clearInterval(streamInterval);
                streamInterval = null;
                messages = messages.map((m) =>
                    m.id === message.id ? { ...m, isStreaming: false } : m
                );
                isProcessing = false;
            }
        }, 30);
    }

    function onQuickAction(question: string) {
        if (isProcessing) return;

        const userMessage: ChatMessage = {
            id: ++messageId,
            content: question,
            isUser: true,
            isStreaming: false,
            streamedContent: question,
        };

        messages = [...messages, userMessage];
        isProcessing = true;
        scrollToBottom();

        setTimeout(() => {
            const aiMessage: ChatMessage = {
                id: ++messageId,
                content: AI_RESPONSES[responseIndex % AI_RESPONSES.length],
                isUser: false,
                isStreaming: true,
                streamedContent: '',
                startTime: Date.now(),
            };

            messages = [...messages, aiMessage];
            responseIndex++;
            startStreamingMessage(aiMessage);
            scrollToBottom();
        }, 500);
    }
</script>
