// apps/demo-svelte/src/components/Home.svelte
<page>
    <actionBar flat={true} class="bg-slate-50">
        <label text="Streamdown" class="font-bold text-lg" />
    </actionBar>

    <scrollView class="bg-slate-50">
        <stackLayout class="pb-8">
            <!-- Hero Section -->
            <stackLayout class="px-6 pt-6 pb-4">
                <label text="@nstudio/nstreamdown" class="text-3xl font-bold text-slate-800" />
                <label
                    text="Native iOS & Android streaming markdown for NativeScript"
                    class="text-base text-slate-500 mt-2 leading-[3]"
                    textWrap={true}
                />
            </stackLayout>

            <!-- Demo Cards -->
            <stackLayout class="px-4">
                {#each demos as demo}
                    <gridLayout
                        columns="auto, *"
                        rows="auto, auto"
                        class="bg-white rounded-2xl p-4 mb-3 shadow-sm"
                        on:tap={() => dispatch('navigate', demo.id)}
                    >
                        <label
                            col="0"
                            row="0"
                            rowSpan="2"
                            text={demo.icon}
                            class={`text-3xl ${demo.color} w-14 h-14 text-center leading-[56] rounded-xl mr-4`}
                        />
                        <label
                            col="1"
                            row="0"
                            text={demo.title}
                            class="text-lg font-semibold text-slate-800"
                        />
                        <label
                            col="1"
                            row="1"
                            text={demo.description}
                            class="text-sm text-slate-500 leading-[3]"
                            textWrap={true}
                        />
                    </gridLayout>
                {/each}
            </stackLayout>

            <!-- Features Section -->
            <label text="Features" class="text-xl font-bold text-slate-800 px-6 mt-6 mb-3" />

            <flexboxLayout
                flexWrap="wrap"
                justifyContent="flex-start"
                class="px-4"
            >
                {#each features as feature}
                    <stackLayout class="w-[30%] bg-white rounded-xl p-3 m-[1.5%] items-center">
                        <label text={feature.icon} class="text-2xl mb-1" />
                        <label text={feature.title} class="text-xs font-medium text-slate-700 text-center" />
                        <label text={feature.desc} class="text-[10] text-slate-400 text-center" />
                    </stackLayout>
                {/each}
            </flexboxLayout>

            <!-- Footer -->
            <stackLayout class="items-center mt-8 px-6">
                <label text="Built with ❤️ by @aspect" class="text-sm text-slate-400" />
                <label text="NativeScript + Svelte" class="text-xs text-slate-300 mt-1" />
            </stackLayout>
        </stackLayout>
    </scrollView>
</page>

<script lang="ts">
    import { createEventDispatcher } from 'svelte';

    const dispatch = createEventDispatcher<{ navigate: string }>();

    const demos = [
        {
            id: 'demo',
            title: 'Streaming Demo',
            description: 'Watch markdown stream in real-time with syntax highlighting',
            icon: '⚡',
            color: 'bg-blue-500',
        },
        {
            id: 'chat',
            title: 'Chat Interface',
            description: 'Interactive chat with AI-style message streaming',
            icon: '💬',
            color: 'bg-emerald-500',
        },
        {
            id: 'charts',
            title: 'Charts',
            description: 'Native iOS & Android charts with DGCharts and MPAndroidChart',
            icon: '📊',
            color: 'bg-purple-500',
        },
    ];

    const features = [
        { icon: '📝', title: 'Full Markdown', desc: 'Headers, lists, tables' },
        { icon: '🎨', title: 'Syntax Highlighting', desc: '50+ languages' },
        { icon: '📐', title: 'Math Support', desc: 'LaTeX equations' },
        { icon: '🔗', title: 'Interactive Links', desc: 'Tappable URLs' },
        { icon: '🌊', title: 'Stream Ready', desc: 'Token-by-token' },
        { icon: '📱', title: 'Native Views', desc: 'iOS & Android' },
        { icon: '🎯', title: 'Accessibility', desc: 'VoiceOver ready' },
        { icon: '🌙', title: 'Dark Mode', desc: 'Theme support' },
        { icon: '📊', title: 'Tables', desc: 'GFM tables' },
        { icon: '✅', title: 'Task Lists', desc: 'Checkboxes' },
    ];
</script>

// apps/demo-vue/src/components/Home.vue
<script lang="ts" setup>
const emit = defineEmits<{
  navigate: [screen: 'demo' | 'chat' | 'charts'];
}>();

interface DemoItem {
  title: string;
  description: string;
  icon: string;
  route: 'demo' | 'chat' | 'charts';
  color: string;
}

const demos: DemoItem[] = [
  {
    title: 'Streaming Demo',
    description: 'Watch markdown render in real-time',
    icon: '⚡',
    route: 'demo',
    color: 'bg-green-100',
  },
  {
    title: 'Chat Interface',
    description: 'Interactive AI chat with streaming',
    icon: '💬',
    route: 'chat',
    color: 'bg-purple-100',
  },
  {
    title: 'Charts',
    description: 'Native iOS & Android charts',
    icon: '📊',
    route: 'charts',
    color: 'bg-blue-100',
  },
];

const features = ['Streaming markdown', 'Incomplete tokens', 'GFM support', 'Code highlighting', 'Tables', 'Math (LaTeX)', 'Images', 'Native performance', 'Dark mode', 'CJK support'];

function getFeatureRow(index: number): number {
  return Math.floor(index / 2);
}

function getFeatureCol(index: number): number {
  return index % 2;
}

function navigateTo(route: 'demo' | 'chat' | 'charts') {
  emit('navigate', route);
}
</script>

<template>
  <Page>
    <ActionBar flat="true" class="bg-slate-50">
      <Label text="nstreamdown" class="text-lg font-bold text-slate-800" />
    </ActionBar>

    <GridLayout rows="*" class="bg-slate-50">
      <ScrollView row="0">
        <StackLayout class="p-4 pt-6">
          <!-- Hero section -->
          <StackLayout class="bg-gradient-to-br from-blue-600 to-purple-700 rounded-2xl p-6 mb-6">
            <Label text="Native iOS Markdown Streaming" class="text-xl text-slate-500 font-bold text-center" />
            <Label text="Real-time AI streaming with beautiful markdown rendering, powered by NativeScript." class="text-sm text-blue-300 text-center mt-2 leading-[3]" textWrap="true" />
          </StackLayout>

          <!-- Demo cards -->
          <Label text="Demos" class="text-xs font-semibold text-slate-400 uppercase tracking-wide mb-3" />

          <StackLayout v-for="demo in demos" :key="demo.route" class="mb-3" @tap="navigateTo(demo.route)">
            <GridLayout columns="48, *, auto" rows="48" class="bg-white rounded-xl p-3 shadow-sm">
              <GridLayout col="0" rows="*" columns="*" :class="'w-12 h-12 rounded-xl ' + demo.color">
                <Label :text="demo.icon" class="text-xl text-center" />
              </GridLayout>
              <GridLayout col="1" rows="auto, auto" class="ml-3">
                <Label row="0" :text="demo.title" class="text-base font-semibold text-slate-800" />
                <Label row="1" :text="demo.description" class="text-xs text-slate-500" textWrap="true" />
              </GridLayout>
              <Label col="2" text="›" class="text-2xl text-slate-300 font-light" />
            </GridLayout>
          </StackLayout>

          <!-- Features list -->
          <Label text="Features" class="text-xs font-semibold text-slate-400 uppercase tracking-wide mt-6 mb-3" />

          <GridLayout columns="*, *" rows="auto, auto, auto, auto, auto" class="bg-white rounded-xl p-4 shadow-sm">
            <GridLayout
              v-for="(feature, index) in features"
              :key="index"
              :row="getFeatureRow(index)"
              :col="getFeatureCol(index)"
              columns="auto, *"
              class="p-2"
            >
              <Label col="0" text="✓" class="text-green-500 text-sm mr-2" />
              <Label col="1" :text="feature" class="text-sm text-slate-600 leading-[3]" textWrap="true" />
            </GridLayout>
          </GridLayout>

          <!-- Footer -->
          <Label text="Inspired by streamdown.ai • Built for NativeScript" class="text-xs text-slate-400 text-center mt-8 mb-4" />
        </StackLayout>
      </ScrollView>
    </GridLayout>
  </Page>
</template>
